### ISSUE TITLE
TS file produced by benchmark is empty

### ISSUE THREAD

**Issue by jdeus** [OP-TEE/optee_os#2553]
Arch: qemu

I modified common.mk to enable benchmarking and rebuilt everything (make all)
When executing the benchmark binary, the TS file produced doesn't contain any timestamp:

benchmark /usr/bin/optee_example_load_call_unload_large 2 2
[Benchmark] INFO: 1. Opening Benchmark Static TA...
[Benchmark] INFO: 2. Allocating per-core buffers, cores detected = 1
[Benchmark] INFO: 3. Starting origin host app /usr/bin/optee_example_load_call_unload_large ...
[Benchmark] INFO: Dumping timestamps to /usr/bin/optee_example_load_call_unload_large.ts ...
_(redacted)_
[Benchmark] INFO: 4. Done benchmark

cat /usr/bin/optee_example_load_call_unload_large.ts
**timestamps: []
...**

The host application invokes the TA so there must be some timestamps there.

**Comment by igoropaniuk** [comment]
```
# benchmark /usr/bin/hello_world 
[Benchmark] INFO: 1. Opening Benchmark Static TA...
[Benchmark] INFO: 2. Allocating per-core buffers, cores detected = 1
[Benchmark] INFO: ts buffer paddr = 7fe00000, size = 792

[Benchmark] INFO: 3. Starting origin host app /usr/bin/hello_world ...
[Benchmark] INFO: Dumping timestamps to /usr/bin/hello_world.ts ...
===================================================================================================================
Invoking TA to increment 42
TA incremented value to 43
[Benchmark] INFO: 4. Done benchmark
# cat /usr/bin/hello_world.ts 
timestamps:
- core: 0
  counter: 31227105600
  address: 0x8058d6ec
  component: kmodule
- core: 0
  counter: 1162344640
  address: 0xe121943
  component: core
- core: 0
  counter: 31227126656
  address: 0x8058d720
  component: kmodule
- core: 0
  counter: 31228175488
  address: 0x8058d6ec
  component: kmodule
- core: 0
  counter: 31228206208
  address: 0x8058d720
  component: kmodule
- core: 0
  counter: 31228613632
  address: 0x8058d6ec
  component: kmodule

```

Any error from SW console?
